export default function experience(): string[] {
    return [
        'Sahaj AI, Bangalore, India - Full-Stack Developer',
        '➢ Developed a platform for uploading and inferring machine learning models, easing the deployment process.',
        '➢ Facilitated model training using cloud computing resources, enhancing scalability and efficiency and knowledge sharing.',
        '➢ Created an in-house solution akin to Hugging Face, providing a comprehensive ecosystem for model management, training and deployment.',
        '\n',
        'Wipro, Bangalore, India - Machine Learning Engineer',
        '➢ Created ML Pipelines to automate several ML models.',
        '➢ Engineered the existing system to train any learning model, allow rapid iteration, monitor singular components with ease, created reusable modules.\n',
        '➢ Automated testing and implemented performance monitoring for feature selection.',
        '\n',
        'ClearlyBlue, Bangalore, India - Machine Learning Intern',
        '➢ Created an IDE.',
        '   ⇢ Developed a text editor where users can write Python code and submit to the server for execution.',
        '   ⇢ Enabled server-side compilation of the Python code using command-line tools like py compile and subprocess module.',
        '   ⇢ Ideated the request and response handling for code input from user and result of execution using Flask web framework.',
        '\n',
        'UpSkale, Bangalore, India - Founder and Full-Stack Developer',
        '',
        '➢ Performance based marketing agency consistently delivered 6-10x ROI.',
        '➢ Built websites, applications and set up infrastructure for small to medium scale businesses.',
        '➢ Sold entity - UpSkale: www.upskale.co.in',
    ]
}