export default function experience(): string[] {
  return [
    "Sahaj AI, Bangalore, India - DevOps Engineer",
    "Owned platform engineering for 70+ developers by improving infrastructure stability, automation and observability.",
    "➢ Achieved zero-downtime deployments with ArgoCD and Crossplane on EKS, using robust GitOps-driven delivery.",
    "➢ Reduced monthly AWS infra costs from $3,000 to $1,200 by implementing vertical pod autoscaling, migrating workloads to",
    "ARM-based instances, and automating scale-down during off-peak hours across internationally distributed servers.",
    "➢ Eliminated weekly outages across clusters through self-healing infrastructure achieving 100% uptime.",
    "➢ Reduced incident resolution time by 50% through improved alerting, monitoring and postmortems enabling focus on platform enhancements.",
    "\n",
    "Sahaj AI, Bangalore, India - Full-Stack Developer",
    "➢ Created an in-house solution akin to Hugging Face, providing a comprehensive lifecycle management for model management, training, and deployment.",
    "➢ Built automated workflows for uploading and inferring machine learning models as containerized Streamlit apps on AWS ECS.",
    "➢ Facilitated ML model training on ephemeral ECS tasks, enabling reproducible training runs, isolated resource environments, and automatic cleanup post-execution.",
    "\n",
    "Wipro, Bangalore, India - Machine Learning Engineer",
    "Designed modular pipelines using MLflow to automate training, monitoring, and hyperparameter tuning for neural networks on traffic datasets.",
    "➢ Refactored existing workflows to support pluggable models and reusable training modules on on-prem servers cutting manual setup time significantly.",
    "➢ Enabled rapid experimentation and improved team efficiency by eliminating repetitive configuration for each training run.  ",
    "\n",
    "ClearlyBlue, Bangalore, India - Machine Learning Intern",
    "➢ Created an IDE.",
    "   ⇢ Developed a text editor where users can write Python code and submit to the server for execution.",
    "   ⇢ Enabled server-side compilation of the Python code using command-line tools like 'py_compile' and 'subprocess' module.",
    "   ⇢ Ideated the request and response handling for code input from user and result of execution using Flask web framework.",
    "\n",
    "UpSkale, Bangalore, India - Founder and Full-Stack Developer",
    "",
    "➢ Performance based marketing agency consistently delivered 6-10x ROI.",
    "➢ Built websites, applications and set up infrastructure for small to medium scale businesses.",
    "➢ Sold entity - UpSkale: www.upskale.co.in",
  ];
}
